// 设置事件类型 即函数名称
export default {
    SET_ROUTEACTION: 'SET_ROUTEACTION',
    SET_LANG: 'SET_LANG',
    SET_USERINFO: 'SET_USERINFO',
    SET_TRANSFERNOTICE: 'SET_TRANSFERNOTICE',
    SET_SYSTEMNOTICE: 'SET_SYSTEMNOTICE',
    SET_SCANDATA: 'SET_SCANDATA',
    SET_CODE: 'SET_CODE',
    SET_NEEDUPDATE: 'SET_NEEDUPDATE',
    SET_UPDATEDETAIL: 'SET_UPDATEDETAIL',
    SET_USERS: 'SET_USERS',
    SET_ADDRESSINFO:'SET_ADDRESSINFO',
    SET_SIDEBARS:'SET_SIDEBARS',
    SET_DEFAULTCATEID:'SET_DEFAULTCATEID'
}
